version: "3"

services:
  app:
    container_name: app
    restart: always
    build: .
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"