#%RAML 1.0
title: Todo List Service
version: v1
baseUri: /auth

types:
	User:
		first_name: string
		last_name: string
		username: string
		password: string

	Message:
		msg: string
	
	Login:
		username: string
		password: string

resourceTypes:
	GET:
		get:
			response:
				200:
					body:
						application/json:
							type: <<item>>
				
				403:
					body:
						application/json:
							type: <<item2>>

	POST:
		post:
			request:
				body:
					application/json:
						type: <<item>>
			respoonse:
				201:
					body:
						application/json:
							type: <<item2>>
				403:
					body:
						application/json:
							type: <<item2>>

/signin:
	type: { POST: {item: Login, item2: Message} }
	description: Login a User if the user is not logged in.

/signup:
	type: { POST: {item: User, item2: Message} }
	description: Create a new user.

/signout:
	description: Logout the user if logged-in.